version: "3.9"

services:
  backend:
    build:
      context: ./Back
    ports:
      - "3000:3000"
    volumes:
      - ./Back:/app
    environment:
      - DENO_ENV=production
    depends_on:
      - database

  # frontend:
  #   build:
  #     context: ./Front
  #   ports:
  #     - "5173:80"
  #   volumes:
  #     - ./Front:/app

  frontend-dev:
    build:
      context: ./Front
      dockerfile: dockerfile.dev # Utiliser le Dockerfile pour le développement
    ports:
      - "5173:5173" # Exposer le port de Vite
    volumes:
      - ./Front:/app # Monter le dossier local pour permettre le hot-reloading
      - /app/node_modules # Éviter les conflits avec les dépendances locales
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]


  database:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: polyculture
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: