version: "3.9"

services:
  backend:
    build:
      context: ./Back
    ports:
      - "3000:3000"
    volumes:
      - ./Back:/app
    environment:
      - DENO_ENV=production

  frontend:
    build:
      context: ./Front
    ports:
      - "5173:80"
    volumes:
      - ./Front:/app

  database:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: polyculture
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: